### ISSUE TITLE
newVelos a little suspicious

### ISSUE THREAD

**Issue by won3d** [pablo-mayrgundter/celestiary#15]
https://github.com/pablo-mayrgundter/celestiary/blob/5c8e5f2b32272cf07a95f450987bb16596acbba8/js/Galaxy.js#L68

- It seems like `newVelos` is really storing accelerations. Maybe rename to `accels`?
- You probably don't want to allocate this anew each time animate is called.
- It might be nicer/faster to use `new Float32Array` which automatically fills things with 0s and will use less storage/bandwidth than a vanilla `Array` which will use 64-bit floats. It also provides some runtime type information that could yield better code generation.

**Comment by pablo-mayrgundter** [comment]
Also fixed in https://github.com/pablo-mayrgundter/celestiary/commit/36f4387bd4d4ce08a4f5865bc1ec9e56d57b1e08#diff-1ab10843cfe0c451bbbd62dc8ec9cc22d33e1e1ac812538d3bb4aea3f7906d5bR61
